appLabel: react-frontend
replicaCount: 2

image:
  repository: react-frontend
  tag: latest
  pullPolicy: Always

container:
  name: react-frontend
  port: 80

service:
  name: react-frontend
  type: ClusterIP  # keep this as ClusterIP for internal communication between services
  # type: LoadBalancer
  port: 80
  targetPort: 80

# probes:
#   liveness:
#     path: /healthz
#     initialDelaySeconds: 5
#     periodSeconds: 30
#   readiness:
#     path: /healthz
#     initialDelaySeconds: 2
#     periodSeconds: 30

config:
  name: frontend-config
  # app2Url: http://fastapi-app-2-service
