{
 "title": "FastAPI App1 - Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"fastapi-app1.*\", container!=\"POD\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Pod Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~\"fastapi-app1-hpa\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"fastapi-app1.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}