appLabel: app1
replicaCount: 2
image:
  # must specify full ECR repository URL for Argo CD to pull the image
  # `tag` will be set by the CD workflow using the commit SHA
  repository: 212135963698.dkr.ecr.us-east-1.amazonaws.com/eks-sandbox-alex/app-1
  tag: 1c62d698e56c672c97d5a9d0dd67761e81eebcdd
  pullPolicy: Always
jwt:
  secretKey: supersecret
  algorithm: HS256
container:
  name: api
  port: 80
portName: http # Single source of truth for port name used by Service and ServiceMonitor
service:
  name: app1-service
  type: ClusterIP # keep this as ClusterIP for internal communication between services
  # type: LoadBalancer
  port: 80
  targetPort: 80
probes:
  livenwess:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 30
  readiness:
    path: /healthz
    initialDelaySeconds: 2
    periodSeconds: 30
config:
  name: app1-config
  app2Url: http://app2-service
  allowedOrigins: http://react-frontend:80
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics
