apiVersion: metallb.io/v1beta1
kind: IPAddressPool  # CRD for MetalLB IP address pool (IPv4/IPv6)
metadata:
  namespace: metallb-system
  name: default-pool
spec:
  addresses:
  - 172.21.0.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement  # Layer 2 adversisement (IPv4/IPv6)
metadata:
  namespace: metallb-system
  name: default
spec:
  ipAddressPools:
  - default-pool