ingress:
  enabled: true
  # If you ever want to change the controller class, do it here
  ingressClassName: nginx-dev  # which ingress controller to use
  annotations:
    kubernetes.io/ingress.class: nginx-dev

apps:
  - name: frontend
    path: /
    pathType: Prefix
    serviceName: react-frontend
    servicePort: 80
