apiVersion: v1
kind: Secret
metadata:
  # The name of the secret, using the Helm release name as a prefix
  name: {{ .Release.Name }}-jwt-secret
type: Opaque  # means this is a generic secret
data:
  # Base64-encoded JWT secret key from values.yaml
  SECRET_KEY: {{ .Values.jwt.secretKey | b64enc | quote }}
  # Base64-encoded JWT algorithm from values.yaml
  ALGORITHM: {{ .Values.jwt.algorithm | b64enc | quote }}
